version: "3.7"
services:
  sql-server:
    container_name: sql-server-db
    image: ysarion/agc_api:v2
    ports:
    - "1433:1433"
    environment:
      SA_PASSWORD: "mySuperStrongP@ssword"
      ACCEPT_EULA: "Y"
